# This file is part of the ReactI18nRouting package.
#
# Copyright (c) 2018-present Friends Of ECMAScript
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8
  - 9
  - 10

install:
    - npm install

script:
    - npm test -- --coverage
    - node_modules/.bin/eslint -c .eslintrc.js src/ tests
    - node_modules/.bin/prettier 'src/**/*.js' 'tests/**/*.js' --list-different all

cache:
    directories:
        - node_modules
